// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(NullifierPIR)
import NullifierPIR
#else
// Define FFI types when framework isn't available (e.g., macOS builds)
// These are stub types that allow compilation but won't work at runtime

public struct RustBuffer {
    public var capacity: UInt64
    public var len: UInt64
    public var data: UnsafeMutablePointer<UInt8>?

    public init(capacity: UInt64, len: UInt64, data: UnsafeMutablePointer<UInt8>?) {
        self.capacity = capacity
        self.len = len
        self.data = data
    }
}

public struct ForeignBytes {
    public var len: Int32
    public var data: UnsafePointer<UInt8>?

    public init(len: Int32, data: UnsafePointer<UInt8>?) {
        self.len = len
        self.data = data
    }
}

public struct RustCallStatus {
    public var code: Int8
    public var errorBuf: RustBuffer
}

// Stub FFI functions for non-iOS platforms
func ffi_nullifier_client_ffi_rustbuffer_from_bytes(_ bytes: ForeignBytes, _ status: UnsafeMutablePointer<RustCallStatus>) -> RustBuffer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func ffi_nullifier_client_ffi_rustbuffer_free(_ buf: RustBuffer, _ status: UnsafeMutablePointer<RustCallStatus>) {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_constructor_pircryptoclient_new(_ status: UnsafeMutablePointer<RustCallStatus>) -> UnsafeMutableRawPointer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_free_pircryptoclient(_ ptr: UnsafeMutableRawPointer, _ status: UnsafeMutablePointer<RustCallStatus>) {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_initialize(_ ptr: UnsafeMutableRawPointer, _ params: RustBuffer, _ status: UnsafeMutablePointer<RustCallStatus>) {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_precompute_keys(_ ptr: UnsafeMutableRawPointer, _ status: UnsafeMutablePointer<RustCallStatus>) {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_generate_query(_ ptr: UnsafeMutableRawPointer, _ nullifierHex: RustBuffer, _ status: UnsafeMutablePointer<RustCallStatus>) -> RustBuffer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_decrypt_response(_ ptr: UnsafeMutableRawPointer, _ responseBytes: RustBuffer, _ nullifierHex: RustBuffer, _ status: UnsafeMutablePointer<RustCallStatus>) -> RustBuffer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_keys_ready(_ ptr: UnsafeMutableRawPointer, _ status: UnsafeMutablePointer<RustCallStatus>) -> Int8 {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_get_protocol(_ ptr: UnsafeMutableRawPointer, _ status: UnsafeMutablePointer<RustCallStatus>) -> RustBuffer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_method_pircryptoclient_get_bucket_indices(_ ptr: UnsafeMutableRawPointer, _ nullifierHex: RustBuffer, _ status: UnsafeMutablePointer<RustCallStatus>) -> RustBuffer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func uniffi_nullifier_client_ffi_fn_clone_pircryptoclient(_ ptr: UnsafeMutableRawPointer, _ status: UnsafeMutablePointer<RustCallStatus>) -> UnsafeMutableRawPointer {
    fatalError("NullifierPIR FFI is not available on this platform")
}

func ffi_nullifier_client_ffi_uniffi_contract_version() -> UInt32 {
    return 26
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_decrypt_response() -> UInt16 {
    return 58388
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_generate_query() -> UInt16 {
    return 62790
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_get_bucket_indices() -> UInt16 {
    return 19026
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_get_protocol() -> UInt16 {
    return 32477
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_initialize() -> UInt16 {
    return 43991
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_keys_ready() -> UInt16 {
    return 47917
}

func uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_precompute_keys() -> UInt16 {
    return 34619
}

func uniffi_nullifier_client_ffi_checksum_constructor_pircryptoclient_new() -> UInt16 {
    return 5706
}
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_nullifier_client_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_nullifier_client_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * PIR crypto client - handles all local cryptographic operations
 */
public protocol PirCryptoClientProtocol : AnyObject {
    
    /**
     * Decrypt PIR response from lightwalletd
     *
     * Takes the response bytes from gRPC InspireQuery() and returns SpentInfo if found
     */
    func decryptResponse(responseBytes: Data, nullifierHex: String) throws  -> FfiSpentInfo?
    
    /**
     * Generate encrypted PIR query for a nullifier
     *
     * Returns query bytes to send to lightwalletd via gRPC InspireQuery()
     */
    func generateQuery(nullifierHex: String) throws  -> FfiPirQuery
    
    /**
     * Get Cuckoo bucket indices for a nullifier
     */
    func getBucketIndices(nullifierHex: String) throws  -> [UInt64]
    
    /**
     * Get the protocol name
     */
    func getProtocol()  -> String
    
    /**
     * Initialize with parameters from lightwalletd GetPirParams response
     */
    func initialize(params: FfiPirParams) throws 
    
    /**
     * Check if keys have been precomputed
     */
    func keysReady()  -> Bool
    
    /**
     * Precompute cryptographic keys (expensive, ~3s for InsPIRe)
     */
    func precomputeKeys() throws 
    
}

/**
 * PIR crypto client - handles all local cryptographic operations
 */
open class PirCryptoClient:
    PirCryptoClientProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_nullifier_client_ffi_fn_clone_pircryptoclient(self.pointer, $0) }
    }
    /**
     * Create a new PIR crypto client
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_nullifier_client_ffi_fn_constructor_pircryptoclient_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_nullifier_client_ffi_fn_free_pircryptoclient(pointer, $0) }
    }

    

    
    /**
     * Decrypt PIR response from lightwalletd
     *
     * Takes the response bytes from gRPC InspireQuery() and returns SpentInfo if found
     */
open func decryptResponse(responseBytes: Data, nullifierHex: String)throws  -> FfiSpentInfo? {
    return try  FfiConverterOptionTypeFfiSpentInfo.lift(try rustCallWithError(FfiConverterTypePirError.lift) {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_decrypt_response(self.uniffiClonePointer(),
        FfiConverterData.lower(responseBytes),
        FfiConverterString.lower(nullifierHex),$0
    )
})
}
    
    /**
     * Generate encrypted PIR query for a nullifier
     *
     * Returns query bytes to send to lightwalletd via gRPC InspireQuery()
     */
open func generateQuery(nullifierHex: String)throws  -> FfiPirQuery {
    return try  FfiConverterTypeFfiPirQuery.lift(try rustCallWithError(FfiConverterTypePirError.lift) {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_generate_query(self.uniffiClonePointer(),
        FfiConverterString.lower(nullifierHex),$0
    )
})
}
    
    /**
     * Get Cuckoo bucket indices for a nullifier
     */
open func getBucketIndices(nullifierHex: String)throws  -> [UInt64] {
    return try  FfiConverterSequenceUInt64.lift(try rustCallWithError(FfiConverterTypePirError.lift) {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_get_bucket_indices(self.uniffiClonePointer(),
        FfiConverterString.lower(nullifierHex),$0
    )
})
}
    
    /**
     * Get the protocol name
     */
open func getProtocol() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_get_protocol(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Initialize with parameters from lightwalletd GetPirParams response
     */
open func initialize(params: FfiPirParams)throws  {try rustCallWithError(FfiConverterTypePirError.lift) {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_initialize(self.uniffiClonePointer(),
        FfiConverterTypeFfiPirParams.lower(params),$0
    )
}
}
    
    /**
     * Check if keys have been precomputed
     */
open func keysReady() -> Bool {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_keys_ready(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Precompute cryptographic keys (expensive, ~3s for InsPIRe)
     */
open func precomputeKeys()throws  {try rustCallWithError(FfiConverterTypePirError.lift) {
    uniffi_nullifier_client_ffi_fn_method_pircryptoclient_precompute_keys(self.uniffiClonePointer(),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePirCryptoClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PirCryptoClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PirCryptoClient {
        return PirCryptoClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PirCryptoClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PirCryptoClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PirCryptoClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePirCryptoClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> PirCryptoClient {
    return try FfiConverterTypePirCryptoClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePirCryptoClient_lower(_ value: PirCryptoClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypePirCryptoClient.lower(value)
}


/**
 * PIR parameters received from lightwalletd
 */
public struct FfiPirParams {
    /**
     * The highest block covered by the PIR database
     */
    public var pirCutoffHeight: UInt64
    /**
     * Protocol name: "inspire" or "ypir"
     */
    public var `protocol`: String
    /**
     * Full parameters as JSON (from lightwalletd GetPirParams response)
     */
    public var paramsJson: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The highest block covered by the PIR database
         */pirCutoffHeight: UInt64, 
        /**
         * Protocol name: "inspire" or "ypir"
         */`protocol`: String, 
        /**
         * Full parameters as JSON (from lightwalletd GetPirParams response)
         */paramsJson: String) {
        self.pirCutoffHeight = pirCutoffHeight
        self.`protocol` = `protocol`
        self.paramsJson = paramsJson
    }
}



extension FfiPirParams: Equatable, Hashable {
    public static func ==(lhs: FfiPirParams, rhs: FfiPirParams) -> Bool {
        if lhs.pirCutoffHeight != rhs.pirCutoffHeight {
            return false
        }
        if lhs.`protocol` != rhs.`protocol` {
            return false
        }
        if lhs.paramsJson != rhs.paramsJson {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pirCutoffHeight)
        hasher.combine(`protocol`)
        hasher.combine(paramsJson)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPirParams: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPirParams {
        return
            try FfiPirParams(
                pirCutoffHeight: FfiConverterUInt64.read(from: &buf), 
                protocol: FfiConverterString.read(from: &buf), 
                paramsJson: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPirParams, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.pirCutoffHeight, into: &buf)
        FfiConverterString.write(value.`protocol`, into: &buf)
        FfiConverterString.write(value.paramsJson, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPirParams_lift(_ buf: RustBuffer) throws -> FfiPirParams {
    return try FfiConverterTypeFfiPirParams.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPirParams_lower(_ value: FfiPirParams) -> RustBuffer {
    return FfiConverterTypeFfiPirParams.lower(value)
}


/**
 * Query to send to lightwalletd
 */
public struct FfiPirQuery {
    /**
     * Serialized query bytes to send via gRPC
     */
    public var queryBytes: Data
    /**
     * Cuckoo bucket indices being queried
     */
    public var bucketIndices: [UInt64]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Serialized query bytes to send via gRPC
         */queryBytes: Data, 
        /**
         * Cuckoo bucket indices being queried
         */bucketIndices: [UInt64]) {
        self.queryBytes = queryBytes
        self.bucketIndices = bucketIndices
    }
}



extension FfiPirQuery: Equatable, Hashable {
    public static func ==(lhs: FfiPirQuery, rhs: FfiPirQuery) -> Bool {
        if lhs.queryBytes != rhs.queryBytes {
            return false
        }
        if lhs.bucketIndices != rhs.bucketIndices {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(queryBytes)
        hasher.combine(bucketIndices)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPirQuery: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPirQuery {
        return
            try FfiPirQuery(
                queryBytes: FfiConverterData.read(from: &buf), 
                bucketIndices: FfiConverterSequenceUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPirQuery, into buf: inout [UInt8]) {
        FfiConverterData.write(value.queryBytes, into: &buf)
        FfiConverterSequenceUInt64.write(value.bucketIndices, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPirQuery_lift(_ buf: RustBuffer) throws -> FfiPirQuery {
    return try FfiConverterTypeFfiPirQuery.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPirQuery_lower(_ value: FfiPirQuery) -> RustBuffer {
    return FfiConverterTypeFfiPirQuery.lower(value)
}


/**
 * Statistics from query operations
 */
public struct FfiQueryStats {
    public var uploadBytes: UInt64
    public var downloadBytes: UInt64
    public var queryGenMs: Double
    public var decryptMs: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uploadBytes: UInt64, downloadBytes: UInt64, queryGenMs: Double, decryptMs: Double) {
        self.uploadBytes = uploadBytes
        self.downloadBytes = downloadBytes
        self.queryGenMs = queryGenMs
        self.decryptMs = decryptMs
    }
}



extension FfiQueryStats: Equatable, Hashable {
    public static func ==(lhs: FfiQueryStats, rhs: FfiQueryStats) -> Bool {
        if lhs.uploadBytes != rhs.uploadBytes {
            return false
        }
        if lhs.downloadBytes != rhs.downloadBytes {
            return false
        }
        if lhs.queryGenMs != rhs.queryGenMs {
            return false
        }
        if lhs.decryptMs != rhs.decryptMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uploadBytes)
        hasher.combine(downloadBytes)
        hasher.combine(queryGenMs)
        hasher.combine(decryptMs)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiQueryStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiQueryStats {
        return
            try FfiQueryStats(
                uploadBytes: FfiConverterUInt64.read(from: &buf), 
                downloadBytes: FfiConverterUInt64.read(from: &buf), 
                queryGenMs: FfiConverterDouble.read(from: &buf), 
                decryptMs: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: FfiQueryStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.uploadBytes, into: &buf)
        FfiConverterUInt64.write(value.downloadBytes, into: &buf)
        FfiConverterDouble.write(value.queryGenMs, into: &buf)
        FfiConverterDouble.write(value.decryptMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQueryStats_lift(_ buf: RustBuffer) throws -> FfiQueryStats {
    return try FfiConverterTypeFfiQueryStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiQueryStats_lower(_ value: FfiQueryStats) -> RustBuffer {
    return FfiConverterTypeFfiQueryStats.lower(value)
}


/**
 * Result of a nullifier spent check
 */
public struct FfiSpentInfo {
    public var blockHeight: UInt64
    public var txIndex: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(blockHeight: UInt64, txIndex: UInt32) {
        self.blockHeight = blockHeight
        self.txIndex = txIndex
    }
}



extension FfiSpentInfo: Equatable, Hashable {
    public static func ==(lhs: FfiSpentInfo, rhs: FfiSpentInfo) -> Bool {
        if lhs.blockHeight != rhs.blockHeight {
            return false
        }
        if lhs.txIndex != rhs.txIndex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blockHeight)
        hasher.combine(txIndex)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSpentInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSpentInfo {
        return
            try FfiSpentInfo(
                blockHeight: FfiConverterUInt64.read(from: &buf), 
                txIndex: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSpentInfo, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.blockHeight, into: &buf)
        FfiConverterUInt32.write(value.txIndex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSpentInfo_lift(_ buf: RustBuffer) throws -> FfiSpentInfo {
    return try FfiConverterTypeFfiSpentInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSpentInfo_lower(_ value: FfiSpentInfo) -> RustBuffer {
    return FfiConverterTypeFfiSpentInfo.lower(value)
}


public enum PirError {

    
    
    case NotInitialized
    case CryptoError(msg: String
    )
    case InvalidInput(msg: String
    )
    case ParamsError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePirError: FfiConverterRustBuffer {
    typealias SwiftType = PirError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PirError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotInitialized
        case 2: return .CryptoError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidInput(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .ParamsError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PirError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotInitialized:
            writeInt(&buf, Int32(1))
        
        
        case let .CryptoError(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .InvalidInput(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .ParamsError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


extension PirError: Equatable, Hashable {}

extension PirError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiSpentInfo: FfiConverterRustBuffer {
    typealias SwiftType = FfiSpentInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiSpentInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiSpentInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_nullifier_client_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_decrypt_response() != 58388) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_generate_query() != 62790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_get_bucket_indices() != 19026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_get_protocol() != 32477) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_initialize() != 43991) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_keys_ready() != 1081) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_method_pircryptoclient_precompute_keys() != 63978) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_nullifier_client_ffi_checksum_constructor_pircryptoclient_new() != 10709) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all